[package]
name = "stylus"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
opentelemetry = { workspace = true }
linkme = { workspace = true }
stylus-macros = { path = "../stylus-macros", version = "0.1.0" }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
opentelemetry_sdk = { workspace = true }
tokio = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "traceable_overhead"
harness = false
