[package]
name = "opentelemetry-traceable"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }

# dependencies, sorted alphabetically
[dependencies]
arc-swap = { workspace = true }
linkme = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-traceable-macros = { path = "../opentelemetry-traceable-macros", version = "0.2.0" }
smallvec = { workspace = true }

# dev dependencies, sorted alphabetically
[dev-dependencies]
criterion = { workspace = true }
opentelemetry-traceable = { path = "." }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-stdout = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }

[[bench]]
name = "traceable_overhead"
harness = false
