//! Static call-graph analysis: augment a catalog *node* dump (`{name, id}`
//! list, from `stylus::catalog::catalog_json`) with `callers`/`callees` edges
//! by parsing the application's source with `syn`.
//!
//! No compilation and no running the app: one linear pass over the `.rs`
//! files. Calls are resolved against the **known node set** only -- a call to
//! a non-`#[traceable]` function is simply not an edge. Resolution is by
//! trailing-path suffix match (e.g. a call written `db::orders::find_by_id`
//! resolves to the node whose full key ends with those segments), refined with
//! the file's `use` imports.
//!
//! ## What it can't see (flagged, not silently dropped)
//!
//! Pure source analysis is blind to dynamic dispatch (`dyn Trait` / trait
//! methods), calls through function pointers or stored closures, and calls
//! generated by macros. Method-call syntax whose name matches a node, and
//! ambiguous path calls, are emitted in `unresolved_calls` (a `file:line`
//! worklist) so the configuring agent can resolve just the ones relevant to
//! its request by reading a little surrounding source -- no MIR needed. Fully
//! macro-generated calls remain an inherent blind spot. Functions given a
//! custom `#[traceable(name = "...")]` key (whose registry key is decoupled
//! from their source path) can't be mapped and get no static edges.

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::Value;
use syn::visit::Visit;

/// A catalog node: its registry key split into `::` segments, plus its id.
struct Node {
    id: u64,
    segs: Vec<String>,
}

/// One statically-unresolvable call inside a traceable function -- the gap
/// worklist the configuring agent fills in from source when relevant.
#[derive(Serialize)]
struct Unresolved {
    /// Id of the traceable function the call appears in.
    in_fn: u64,
    /// Registry key of that function, for convenience.
    in_fn_name: String,
    /// `file:line` of the call site.
    site: String,
    /// The call as written (e.g. `x.send(...)` -> `send` (method call)).
    call: String,
    /// Reason it couldn't be resolved.
    reason: &'static str,
    /// Node ids that *could* be the target (e.g. every node whose name ends
    /// with the called method), for the agent to choose among.
    candidates: Vec<u64>,
}

/// Run the analysis and return the augmented catalog JSON (pretty-printed).
pub fn run(catalog_path: &Path, src_dir: &Path) -> Result<String, Box<dyn Error>> {
    let raw = fs::read_to_string(catalog_path)
        .map_err(|e| format!("reading catalog `{}`: {e}", catalog_path.display()))?;
    let mut catalog: Value = serde_json::from_str(&raw)
        .map_err(|e| format!("parsing catalog `{}`: {e}", catalog_path.display()))?;

    let functions = catalog
        .get("functions")
        .and_then(Value::as_array)
        .ok_or("catalog has no `functions` array")?;
    let nodes: Vec<Node> = functions
        .iter()
        .filter_map(|f| {
            let name = f.get("name")?.as_str()?;
            let id = f.get("id")?.as_u64()?;
            Some(Node {
                id,
                segs: name.split("::").map(str::to_owned).collect(),
            })
        })
        .collect();
    if nodes.len() != functions.len() {
        return Err("every catalog function needs a string `name` and integer `id`".into());
    }
    let name_by_id: BTreeMap<u64, String> =
        nodes.iter().map(|n| (n.id, n.segs.join("::"))).collect();

    let mut callees: BTreeMap<u64, BTreeSet<u64>> = BTreeMap::new();
    let mut unresolved: Vec<Unresolved> = Vec::new();

    for file in rust_files(src_dir)? {
        analyze_file(
            &file,
            src_dir,
            &nodes,
            &name_by_id,
            &mut callees,
            &mut unresolved,
        )?;
    }

    // Derive callers from callees.
    let mut callers: BTreeMap<u64, BTreeSet<u64>> = BTreeMap::new();
    for (&caller, targets) in &callees {
        for &callee in targets {
            callers.entry(callee).or_default().insert(caller);
        }
    }

    // Write edges back into each function object.
    if let Some(arr) = catalog.get_mut("functions").and_then(Value::as_array_mut) {
        for f in arr.iter_mut() {
            let Some(id) = f.get("id").and_then(Value::as_u64) else {
                continue;
            };
            let obj = f.as_object_mut().expect("catalog functions are objects");
            obj.insert("callers".into(), ids_to_value(callers.get(&id)));
            obj.insert("callees".into(), ids_to_value(callees.get(&id)));
        }
    }
    unresolved.sort_by(|a, b| a.site.cmp(&b.site));
    catalog
        .as_object_mut()
        .expect("catalog is a JSON object")
        .insert(
            "unresolved_calls".into(),
            serde_json::to_value(&unresolved)?,
        );

    Ok(serde_json::to_string_pretty(&catalog)?)
}

fn ids_to_value(ids: Option<&BTreeSet<u64>>) -> Value {
    Value::Array(
        ids.into_iter()
            .flatten()
            .map(|&id| Value::from(id))
            .collect(),
    )
}

/// Every `.rs` file under `dir`, recursively.
fn rust_files(dir: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(path) = stack.pop() {
        for entry in
            fs::read_dir(&path).map_err(|e| format!("reading `{}`: {e}", path.display()))?
        {
            let entry = entry?;
            let p = entry.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().is_some_and(|e| e == "rs") {
                out.push(p);
            }
        }
    }
    out.sort();
    Ok(out)
}

/// Module segments implied by a file's path relative to the source root:
/// `src/domain/db.rs` -> `[domain, db]`, `src/foo/mod.rs` -> `[foo]`,
/// `src/{main,lib}.rs` -> `[]`.
fn base_mods(file: &Path, src_dir: &Path) -> Vec<String> {
    let rel = file.strip_prefix(src_dir).unwrap_or(file);
    let mut segs: Vec<String> = rel
        .components()
        .map(|c| c.as_os_str().to_string_lossy().into_owned())
        .collect();
    if let Some(last) = segs.last_mut() {
        *last = last.trim_end_matches(".rs").to_owned();
    }
    if matches!(
        segs.last().map(String::as_str),
        Some("mod" | "main" | "lib")
    ) {
        segs.pop();
    }
    segs
}

fn analyze_file(
    file: &Path,
    src_dir: &Path,
    nodes: &[Node],
    name_by_id: &BTreeMap<u64, String>,
    callees: &mut BTreeMap<u64, BTreeSet<u64>>,
    unresolved: &mut Vec<Unresolved>,
) -> Result<(), Box<dyn Error>> {
    let content =
        fs::read_to_string(file).map_err(|e| format!("reading `{}`: {e}", file.display()))?;
    let Ok(parsed) = syn::parse_file(&content) else {
        // A file we can't parse (odd cfg, unstable syntax) is skipped rather
        // than failing the whole run.
        return Ok(());
    };

    let mut uses: BTreeMap<String, Vec<String>> = BTreeMap::new();
    collect_uses(&parsed.items, &mut uses);

    let ctx = FileCtx {
        file_display: file
            .strip_prefix(src_dir)
            .unwrap_or(file)
            .display()
            .to_string(),
        nodes,
        name_by_id,
        uses: &uses,
    };
    let mut mods = base_mods(file, src_dir);
    walk_items(&parsed.items, &mut mods, &ctx, callees, unresolved);
    Ok(())
}

struct FileCtx<'a> {
    file_display: String,
    nodes: &'a [Node],
    name_by_id: &'a BTreeMap<u64, String>,
    uses: &'a BTreeMap<String, Vec<String>>,
}

/// Collect non-glob `use` leaves (and `as` renames) from all items, mapping
/// the in-scope name to its full `::` path. Globs are ignored (can't expand).
fn collect_uses(items: &[syn::Item], out: &mut BTreeMap<String, Vec<String>>) {
    for item in items {
        match item {
            syn::Item::Use(u) => collect_use_tree(&u.tree, &mut Vec::new(), out),
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    collect_uses(inner, out);
                }
            }
            _ => {}
        }
    }
}

fn collect_use_tree(
    tree: &syn::UseTree,
    prefix: &mut Vec<String>,
    out: &mut BTreeMap<String, Vec<String>>,
) {
    match tree {
        syn::UseTree::Path(p) => {
            prefix.push(p.ident.to_string());
            collect_use_tree(&p.tree, prefix, out);
            prefix.pop();
        }
        syn::UseTree::Name(n) => {
            let mut full = prefix.clone();
            full.push(n.ident.to_string());
            out.insert(n.ident.to_string(), full);
        }
        syn::UseTree::Rename(r) => {
            let mut full = prefix.clone();
            full.push(r.ident.to_string());
            out.insert(r.rename.to_string(), full);
        }
        syn::UseTree::Group(g) => {
            for t in &g.items {
                collect_use_tree(t, prefix, out);
            }
        }
        syn::UseTree::Glob(_) => {}
    }
}

fn walk_items(
    items: &[syn::Item],
    mods: &mut Vec<String>,
    ctx: &FileCtx,
    callees: &mut BTreeMap<u64, BTreeSet<u64>>,
    unresolved: &mut Vec<Unresolved>,
) {
    for item in items {
        match item {
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    mods.push(m.ident.to_string());
                    walk_items(inner, mods, ctx, callees, unresolved);
                    mods.pop();
                }
            }
            syn::Item::Fn(f) if is_traceable(&f.attrs) => {
                handle_fn(&f.sig.ident, &f.block, mods, ctx, callees, unresolved);
            }
            syn::Item::Impl(imp) => {
                for ii in &imp.items {
                    if let syn::ImplItem::Fn(m) = ii
                        && is_traceable(&m.attrs)
                    {
                        handle_fn(&m.sig.ident, &m.block, mods, ctx, callees, unresolved);
                    }
                }
            }
            _ => {}
        }
    }
}

fn is_traceable(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| {
        a.path()
            .segments
            .last()
            .is_some_and(|s| s.ident == "traceable")
    })
}

fn handle_fn(
    ident: &syn::Ident,
    block: &syn::Block,
    mods: &[String],
    ctx: &FileCtx,
    callees: &mut BTreeMap<u64, BTreeSet<u64>>,
    unresolved: &mut Vec<Unresolved>,
) {
    // Identify this function's node by suffix-matching [mods.., fn_name].
    let mut own = mods.to_vec();
    own.push(ident.to_string());
    let matches = suffix_matches(ctx.nodes, &own);
    let [caller_id] = matches[..] else {
        // Not a node (or a custom-named one we can't map): no edges from here.
        return;
    };

    let mut collector = CallCollector::default();
    collector.visit_block(block);

    let in_fn_name = ctx.name_by_id.get(&caller_id).cloned().unwrap_or_default();
    for call in collector.calls {
        match call.kind {
            CallKind::Path(segs) => {
                let expanded = expand(&segs, ctx.uses);
                match suffix_matches(ctx.nodes, &expanded)[..] {
                    [] => {} // not a traceable target
                    [callee] => {
                        if callee != caller_id {
                            callees.entry(caller_id).or_default().insert(callee);
                        }
                    }
                    ref many => unresolved.push(Unresolved {
                        in_fn: caller_id,
                        in_fn_name: in_fn_name.clone(),
                        site: format!("{}:{}", ctx.file_display, call.line),
                        call: format!("{}(...)", segs.join("::")),
                        reason: "ambiguous path (multiple traceable functions match)",
                        candidates: many.to_vec(),
                    }),
                }
            }
            CallKind::Method(name) => {
                let cands = suffix_matches(ctx.nodes, std::slice::from_ref(&name));
                if !cands.is_empty() {
                    unresolved.push(Unresolved {
                        in_fn: caller_id,
                        in_fn_name: in_fn_name.clone(),
                        site: format!("{}:{}", ctx.file_display, call.line),
                        call: format!("<receiver>.{name}(...)"),
                        reason: "method call (receiver type unknown to static analysis)",
                        candidates: cands,
                    });
                }
            }
        }
    }
}

/// Node ids whose segment list ends with `needle`.
fn suffix_matches(nodes: &[Node], needle: &[String]) -> Vec<u64> {
    if needle.is_empty() {
        return Vec::new();
    }
    nodes
        .iter()
        .filter(|n| ends_with(&n.segs, needle))
        .map(|n| n.id)
        .collect()
}

fn ends_with(hay: &[String], needle: &[String]) -> bool {
    needle.len() <= hay.len() && hay[hay.len() - needle.len()..] == *needle
}

/// Expand a written call path using `use` imports and strip `crate`/`self`/
/// `super` markers, so it can be suffix-matched against full node keys.
fn expand(path: &[String], uses: &BTreeMap<String, Vec<String>>) -> Vec<String> {
    let mut p: Vec<String> = path.iter().filter(|s| *s != "super").cloned().collect();
    while matches!(p.first().map(String::as_str), Some("crate" | "self")) {
        p.remove(0);
    }
    if let Some(first) = p.first()
        && let Some(full) = uses.get(first)
    {
        let mut expanded = full.clone();
        expanded.extend_from_slice(&p[1..]);
        while matches!(expanded.first().map(String::as_str), Some("crate" | "self")) {
            expanded.remove(0);
        }
        return expanded;
    }
    p
}

#[derive(Default)]
struct CallCollector {
    calls: Vec<CallSite>,
}

struct CallSite {
    kind: CallKind,
    line: usize,
}

enum CallKind {
    Path(Vec<String>),
    Method(String),
}

impl<'ast> Visit<'ast> for CallCollector {
    fn visit_expr_call(&mut self, node: &'ast syn::ExprCall) {
        if let syn::Expr::Path(p) = &*node.func {
            let segs: Vec<String> = p
                .path
                .segments
                .iter()
                .map(|s| s.ident.to_string())
                .collect();
            if !segs.is_empty() {
                self.calls.push(CallSite {
                    line: p.path.segments[0].ident.span().start().line,
                    kind: CallKind::Path(segs),
                });
            }
        }
        syn::visit::visit_expr_call(self, node);
    }

    fn visit_expr_method_call(&mut self, node: &'ast syn::ExprMethodCall) {
        self.calls.push(CallSite {
            line: node.method.span().start().line,
            kind: CallKind::Method(node.method.to_string()),
        });
        syn::visit::visit_expr_method_call(self, node);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nodes(names: &[&str]) -> Vec<Node> {
        names
            .iter()
            .enumerate()
            .map(|(i, n)| Node {
                id: i as u64,
                segs: n.split("::").map(str::to_owned).collect(),
            })
            .collect()
    }

    fn analyze(
        content: &str,
        base: &[&str],
        nodes: &[Node],
    ) -> (BTreeMap<u64, BTreeSet<u64>>, Vec<Unresolved>) {
        let parsed = syn::parse_file(content).unwrap();
        let mut uses = BTreeMap::new();
        collect_uses(&parsed.items, &mut uses);
        let name_by_id: BTreeMap<u64, String> =
            nodes.iter().map(|n| (n.id, n.segs.join("::"))).collect();
        let ctx = FileCtx {
            file_display: "x.rs".into(),
            nodes,
            name_by_id: &name_by_id,
            uses: &uses,
        };
        let mut mods: Vec<String> = base.iter().map(|s| s.to_string()).collect();
        let mut callees = BTreeMap::new();
        let mut unresolved = Vec::new();
        walk_items(
            &parsed.items,
            &mut mods,
            &ctx,
            &mut callees,
            &mut unresolved,
        );
        (callees, unresolved)
    }

    #[test]
    fn resolves_qualified_calls_via_suffix_and_use() {
        let nodes = nodes(&[
            "app::scenarios::checkout",            // 0
            "app::domain::db::orders::find_by_id", // 1
            "app::domain::db::users::find_by_id",  // 2
            "app::domain::auth::rate_limit_check", // 3
        ]);
        let src = r#"
            use app::domain::{db, auth};
            #[traceable]
            fn checkout() {
                auth::rate_limit_check();
                db::orders::find_by_id();
                helper();            // not a node -> ignored
            }
        "#;
        let (callees, unresolved) = analyze(src, &["scenarios"], &nodes);
        let from_checkout = &callees[&0];
        assert!(from_checkout.contains(&3), "auth::rate_limit_check edge");
        assert!(from_checkout.contains(&1), "db::orders::find_by_id edge");
        assert!(
            !from_checkout.contains(&2),
            "must not match the users:: one"
        );
        assert!(unresolved.is_empty(), "clean direct calls, no gaps");
    }

    #[test]
    fn flags_method_calls_matching_a_node_name() {
        let nodes = nodes(&["app::external::sms::send", "app::x::notify"]);
        let src = r#"
            #[traceable]
            fn notify() {
                let client = make();
                client.send("hi");    // dynamic dispatch -> flagged, not an edge
            }
        "#;
        let (callees, unresolved) = analyze(src, &["x"], &nodes);
        assert!(callees.is_empty(), "method call is not resolved to an edge");
        assert_eq!(unresolved.len(), 1);
        assert_eq!(
            unresolved[0].candidates,
            vec![0],
            "sms::send is the candidate"
        );
    }
}
